baseURL = "http://shreyas-shankar.github.io"
languageCode = "en-us"
title = "Shreyas Shankar"
theme = "minimal"

[params]
    author = "hi i'm shreyas"
    hi = "Hi."
    description1 = "I'm Shreyas."
    description2 = "I'm a Computer Science Graduate Student at the University of Southern California, Los Angeles."
    description3 = "Previously, I worked as a Solutions Architect at Akamai Technologies in Bangalore, India."
    description4 = "A link to my GitHub repo"
    description5 = "You can contact me by email"
    githubUsername = "shreyas-shankar"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Quicksand" # should match the name on Google Fonts!
    fontOptions = ":400,700"
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

# [[menu.main]]
#     url = "/post/"
#     name = "Posts"
#     weight = 2
#
# [[menu.main]]
#     url = "/project/"
#     name = "Projects"
#     weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/



[[menu.icon]]
    url = "https://github.com/shreyas-shankar/"
    name = "github"
    weight = 2



[[menu.icon]]
    url = "https://www.linkedin.com/in/shreyas-shankar-37636053"
    name = "linkedin"
    weight = 4
